### ISSUE TITLE
pty.js

### ISSUE THREAD

**Issue by stevenvachon** [jonschlinkert/window-size#14]
With [pty.js](https://npmjs.com/pty.js), the value of this library is `undefined`.

**Comment by jonschlinkert** [comment]
@stevenvachon I'm not at all familiar with `pty.js`. Given that it's just a library, not a standard, this seems like something you'd need to dig into yourself. A quick search yielded the following:  https://github.com/chjj/pty.js/commit/07a7efc3f3c8938c171af3297e179334fc0bf150. Perhaps this is related to a solution. 

closing since this doesn't seem related to window-size. if it is, please provide more information about specifically what is causing the bug along with a stack trace and information necessary for anyone else to reproduce the bug.

**Comment by stevenvachon** [comment]
https://github.com/enquirer/readline-utils/issues/4
