### ISSUE TITLE
React to window size changes?

### ISSUE THREAD

**Issue by danfuzz** [jonschlinkert/window-size#7]
It would be great if this module didn't just set width and height once at initial load time, and instead noticed dynamic changes.

Thanks for your consideration.

**Comment by jonschlinkert** [comment]
I think I have a branch locally where I played around with this. I'll get something pushed up in the next few days (I have one or two other things queued up, after that I can work on this)

**Comment by derhuerst** [comment]
@jonschlinkert Would be great if you pushed this! The module seems a lot less useful without this!

Maybe keep exporting `size.width` and `size.height`, but make `size` an function that returns a new, up-to-date `{width: …, height: …}`. This way the change would be backwards-compatible.

**Comment by jonschlinkert** [comment]
see https://github.com/jonschlinkert/window-size/tree/refactor. Let me know if this works for you, also interested in feedback from @bcoe. For backwards compatibility, the main export is still an object, but a `.create()` method is exposed so that it can be called to get up-to-date size info on demand (I'll also need to re-add the [windows code](https://github.com/jonschlinkert/window-size/blob/master/index.js#L31) unless we can find a better solution, but I wanted to get some feedback on the approach first).

**Comment by derhuerst** [comment]
I think you shouldn't use `execSync`. It blocks the event loop for an unknown amount of time.

**Comment by derhuerst** [comment]
👍 for `.create()`, although i'd prefer a name like `get`, `compute` or `query`.

**Comment by jonschlinkert** [comment]
> think you shouldn't use execSync. It blocks the event loop for an unknown amount of time.

want to do a pr for that code? I'd happily accept one!

> for .create(), although i'd prefer a name like get, compute or query.

`.compute` seems fine, thanks

**Comment by derhuerst** [comment]
>> think you shouldn't use execSync. It blocks the event loop for an unknown amount of time.
>
> want to do a pr for that code? I'd happily accept one!

This will make the whole function async. Do you prefer `async`, `Promise`s or Node-style callbacks?

**Comment by jonschlinkert** [comment]
> This will make the whole function async.

ah, neither. I don't mind adding async, but we'll need to continue supporting sync for windows. If you have a better alternative to `.execSync` for that I'm open to it, but otherwise we'll need to use it

**Comment by derhuerst** [comment]
> ah, neither. I don't mind adding async, but we'll need to continue supporting sync for windows.

Why? Because `0.3` is supposed to keep working on windows?

**Comment by jonschlinkert** [comment]
> Why?

the first reason: "Because 0.3 is supposed to keep working on windows (without introducing breaking changes)". `.execSync` is not without problems, but it's better than nothing. I really don't want to alienate windows users - microsoft is getting a lot better these days, I'd like to show love where we can.

**Comment by derhuerst** [comment]
If we bump the version, we can safely introduce `exec`, right?

**Comment by bcoe** [comment]
@jonschlinkert thanks for looping me in on this ... don't quite know how you'd pull it off, but it would definitely be interesting to have yargs dynamically change terminal size.

If this is a pretty big refactor, could I ask that it's released as a major bump? that way we can be mindful pulling it into yargs.

**Comment by jonschlinkert** [comment]
> could I ask that it's released as a major bump?

absolutely, changes like this would definitely be a major.

**Comment by derhuerst** [comment]
> see https://github.com/jonschlinkert/window-size/tree/refactor. […] For backwards compatibility, the main export is still an object, but a `.create()` method is exposed

nope, seems like `create` should have been assigned to `module.exports`. please provide this! (:
